### PR TITLE
Add overflow hidden to remove scroll when zooming

### PR DESCRIPTION
**Pull request by IceInBeard**
Add overflow hidden to remove scroll when zooming

### CODE REVIEW

**Comment by mikeduminy** [comment]
PLEASE MERGE THIS, CURRENTLY BROKEN

**Comment by shofman** [comment]
Did you test on IE 6?

**Comment by IceInBeard** [comment]
> Did you test on IE 6?

Maybe 😇

**Comment by IceInBeard** [comment]
> Did you test on IE 6?

Problem solved : https://github.com/shofman/shofman.github.io/pull/3

**Pull request merged**
